# [general]

machine=imx8mpcartzy

UBOOT_CONFIG="imx8mp_evk_defconfig"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx8mpcartzy/flash.bin"

# distro boot script
# dummy value, real boot script is provided by Cartzy boot overlay
distro_bootscript="bsp/u-boot/imx8mpevk/imx8mpevk_boot.scr"

# Cartzy boot overlay (boot.txt/uEnv.txt)
if [ -z "$CARTZY_SYSTEM_PATH" ]; then
    echo "CARTZY_SYSTEM_PATH is not set. Export it before build." >&2
    exit 1
fi
BOOT_OVERLAY_DIR="$CARTZY_SYSTEM_PATH/imx8/os/boot"

# Keep only required DTBs in boot partition
BOOT_DTB_LIST="imx8mp-cartzy-v1.dtb"

# Copy cartzy_system files to rootfs
CARTZY_COPY_TO_ROOTFS=1

# # Sound Open Firmware Zephyr build is skipped for this board
# SKIP_SOF_ZEPHYR=1

# TODO: Check packages debian_desktop_arm64.yaml
DISTROTYPE=debian
DISTROVARIANT=desktop
FRAGMENT_CFG_OVERRIDE="imx8mpcartzy_override.config"
